copy /Y "D:\home\site\wwwroot\build" "D:\home\site\"
rmdir /S /Q "D:\home\site\wwwroot\src"
rmdir /S /Q "D:\home\site\wwwroot\public"
rmdir /S /Q "D:\home\site\wwwroot\.vscode"
rmdir /S /Q "D:\home\site\wwwroot\.github"
del /F /Q "D:\home\site\wwwroot\.gitignore"
del /F /Q "D:\home\site\wwwroot\CloudDrive.code-workspace"
del /F /Q "D:\home\site\wwwroot\ContributerCodeOfConduct.md"
del /F /Q "D:\home\site\wwwroot\PULL_REQUEST_TEMPLATE.md"
rmdir /S /Q "D:\home\site\wwwroot\scripts"
rmdir /S /Q "D:\home\site\wwwroot"
copy "D:\home\site\wwwroot\build" "D:\home\site\wwwroot"